name: citest
on:
  push:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
jobs:
  tests:
    runs-on: ['self-hosted']
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/run
      with:
          command: echo "Hello World"
