name: citest
on:
  push:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

env:
  RUNNER_DEBUG: 1

jobs:
  tests:
    runs-on: ['self-hosted', 'linux', 'shared-runner-ephemeral']
    steps:
    - uses: actions/checkout@v3
    - uses: synced-actions/satackey-action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: foo-docker-cache-{hash}
        restore-keys: |
          foo-docker-cache-
    - uses: ./.github/actions/run
      with:
          command: echo "Hello World"
